// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJpd9r9B1GbXqd4rHOlXyclJ69SoZnvU',
    appId: '1:864967836799:web:663531a79d9614872deb4a',
    messagingSenderId: '864967836799',
    projectId: 'flutter-firebase-auth-89d0f',
    authDomain: 'flutter-firebase-auth-89d0f.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-89d0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmrIoaUJvqbaQkUChzIleb_Vi7Gv61fo',
    appId: '1:864967836799:android:8668697e1e0ebad52deb4a',
    messagingSenderId: '864967836799',
    projectId: 'flutter-firebase-auth-89d0f',
    storageBucket: 'flutter-firebase-auth-89d0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KNxrY4u49oTwRRQQZXuHP7Yt1XmQ_0Q',
    appId: '1:864967836799:ios:d6b50b1d2a2543282deb4a',
    messagingSenderId: '864967836799',
    projectId: 'flutter-firebase-auth-89d0f',
    storageBucket: 'flutter-firebase-auth-89d0f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

}